DATA:
  data_root: data/point_cloud_label_3d/nuscenes_autra_3d_dataset_v2
  data_root_2d_fused_feature: data/text_feature_3d/nuscenes_autra_3d_dataset_v2
  #train_dataset_list: ['autra_eval_m1.1','autra_eval_m1.2','autra_train_case_m1.1','autra_train_case_m1.2','autra_train_case_v1.0','autra_train_case_v1.1','autra_train_case_v1.10','autra_train_case_v1.11','autra_train_case_v1.12','autra_train_case_v1.13','autra_train_case_v1.14','autra_train_case_v1.2','autra_train_case_v1.3','autra_train_case_v1.4','autra_train_case_v1.5','autra_train_case_v1.6','autra_train_case_v1.7','autra_train_case_v1.8','autra_train_case_v1.9','autra_train_m1.1','autra_train_m1.2_A001-20230504_122324','autra_train_m1.2_A001-20230504_142550','autra_train_m1.2_A001-20230517_140015','autra_train_m1.3','autra_train_m1.4','autra_train_m1.6','autra_train_m1.7','autra_train_m1.8','autra_train_v2.11','autra_train_v2.12','autra_train_v2.13','autra_train_v2.14','autra_train_v2.15','autra_train_v2.16','autra_train_v2.17','autra_train_v2.18','autra_train_v2.19','autra_train_v2.20','autra_train_v2.21','autra_train_v2.22','autra_train_v2.23','autra_train_v2.24','autra_train_v2.25','autra_train_v2.27','autra_train_v2.28','autra_train_v2.29','autra_train_v2.30','autra_train_v2.31','autra_train_v2.32']
  #eval_dataset_list: ['autra_eval_v2.06', 'autra_eval_v2.07', 'autra_eval_v2.08']
  train_dataset_list: ['autra_train_case_v1.10','autra_train_case_v1.11']
  eval_dataset_list: ['autra_eval_v2.07', 'autra_train_case_v1.12']
  feature_2d_extractor: openseg
  classes: 6
  aug: False
  voxel_size: 0.05
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: -1
  #train_gpu: [0,1,2,3]
  train_gpu: [0,1,2,3]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  focal_loss_weight: 1.5
  loop: 1
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 50
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 2

TEST:
  split: val  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  vis_input: False
  vis_pred: True
  vis_gt: False
  test_workers: 1
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 1
  model_path: /home/fan.ling/big_model/OpenScene/OpenScene/exp_dir/lingfan_autra_detect_dem_distill_0808_10W_focal_1.5/model/model_last.pth.tar
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
