DATA:
  data_root: data/point_cloud_label_3d/nuscenes_autra_3d_dataset_v3
  data_root_2d_fused_feature: data/text_feature_3d/nuscenes_autra_3d_dataset_v3
  train_dataset_list: ['ACRush-20230727_050340','ACRush-20230728_002121', "James-20230629_135448", "Mbappe-20230727_073216", "Robin-20230726_122052"]
  eval_dataset_list: ['autra_seg_eval_v1.01']
  clip_dim: 768
  classes: 6
  aug: False
  voxel_size: 0.05
  input_feature: True
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: -1
  train_gpu: [0,1,2,3,4,5,6,7]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 16  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.00001
  loss_type: cosine # l1 | cosine
  focal_loss_weight: 1.5
  loop: 1
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 50
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 2

TEST:
  split: val  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'distill' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  vis_input: False
  vis_pred: True
  vis_gt: False
  test_workers: 1
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 1
  model_path: /home/fan.ling/big_model/OpenScene/OpenScene/exp_dir/autra_pretrain_focal_1.5_epoch_50_0822/model/model_last.pth.tar
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
